language: node_js
node_js:
  - stable
  - 8
  - 6
script:
  - npm test
compiler: clang-4.0
env:
  global:
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CC="clang"
    - CXX="clang++"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev
notifications:
  email: false
